---
title: "1. Basic R"
author: "Vestin Hategekimana"
description: "Exercises for absolute beginners O.o"
engine: knitr
format: live-html
---

{{< include ../../_extensions/r-wasm/live/_knitr.qmd >}}

## Exercise 1: Basic Arithmetic

Calculate the sum of 15 and 30.

**Solution:**
```{webr}
#| exercise: ex_1

```

::: { .hint exercise="ex_1"}
::: { .callout-note collapse="false"}
## Hint

Use the `+` operator to add two numbers like a machine calculator.
:::
:::

::: { .solution exercise="ex_1" }
::: { .callout-tip collapse="false"}
## Solution:
```r
15 + 30
```

:::
:::

## Exercise 2: Variable Assignment

Assign the value 100 to a variable named `my_variable` and print it.

```{webr}
#| exercise: ex_2

```

::: { .hint exercise="ex_2"}
::: { .callout-note collapse="false"}
## Hint

Use the `<-` (or `=`) operator to assign a value to a variable.
:::
:::


::: { .solution exercise="ex_2" }
::: { .callout-tip collapse="false"}
## Solution:

```r
# Assign value to a variable
my_variable <- 100

# or
my_variable = 100

# Print the variable
my_variable
```
:::
:::

## Exercise 3: Creating a Vector

Create a vector named `my_vector` containing the numbers 1, 2, 3, 4, and 5.

```{webr}
#| exercise: ex_3

```


::: { .hint exercise="ex_3"}
::: { .callout-note collapse="false"}
## Hint
Use the `c()` function to create a vector.
:::
:::

::: { .hint exercise="ex_3"}
::: { .callout-note collapse="false"}
## Tips
Alternatively use the `:` function to create a vector.
:::
:::

::: { .solution exercise="ex_3" }
::: { .callout-tip collapse="false"}
## Solution:

```r
# Create a vector
c(1, 2, 3, 4, 5)

# or
1:5
```
:::
:::

## Exercise 4: Basic Function Usage

Find the mean of the numbers 10, 20, 30, 40, and 50.

```{webr}
#| exercise: ex_4
numbers <- c(10, 20, 30, 40, 50)
```

::: { .hint exercise="ex_4"}
::: { .callout-note collapse="false"}
## Hint 
Use the `mean()` function to calculate the average of a set of numbers.
:::
:::

::: { .solution exercise="ex_4" }
::: { .callout-tip collapse="false"}
## Solution:
```r
# Calculate the mean
numbers <- c(10, 20, 30, 40, 50)
mean(numbers)
```
:::
:::

## Exercise 5: Conditional Statement

Write a conditional statement that checks if a number `x` is greater than 10. If it is, print "Greater than 10"; otherwise, print "10 or less".

```{webr}
#| exercise: ex_5
x <- 12
```


::: { .hint exercise="ex_5"}
::: { .callout-note collapse="false"}
## Hint 
Use an `if` statement to perform a conditional check.
:::
:::

::: { .solution exercise="ex_5" }
::: { .callout-tip collapse="false"}
**Solution:**
```r
x <- 12

# Conditional statement
if (x > 10) {
  print("Greater than 10")
} else {
  print("10 or less")
}
```
:::
:::